server:
  port: 8080

spring:
  data:
    mongodb:
      database: flixbus_url_shortener
      url: mongodb+srv://.odba7.mongodb.net/flixbus_url_shortener?retryWrites=true&w=majority
      auto-index-creation: true

