server:
  port: 8080

spring:
  data:
    mongodb:
      database: render-test
      url: mongodb+srv://testuser:7wwSdQvIMOlu6QV2@render-test.97njqdq.mongodb.net/?retryWrites=true&w=majority
      auto-index-creation: true

