server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://testuser:7wwSdQvIMOlu6QV2@render-test.97njqdq.mongodb.net/url-shortener?retryWrites=true&w=majority
      auto-index-creation: true

